name: Deploy Project
# set the event for this project to run
on: push
jobs: 
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        # to use an action, use the 'uses' keyword
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        # some actions require some configuration which can be specified by the 'with' keyword
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
  # run a second job, testing multiple jobs
  deploy:
    # To run job sequentially, use the 'needs' keyword
    # To wait for multiple jobs to run, use and array [job1, job2, job3]
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        # to use an action, use the 'uses' keyword
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        # some actions require some configuration which can be specified by the 'with' keyword
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
        # build the project before deployment
      - name: Build project
        run: npm run build
      - name: Deploy
        run: echo "Deploying ..."

